FROM python:3.13-slim

WORKDIR /workspace

# Writable cache
RUN mkdir -p /workspace/.cache && chmod -R 777 /workspace
ENV HF_HOME=/workspace/.cache
ENV TRANSFORMERS_CACHE=/workspace/.cache/huggingface
ENV SENTENCE_TRANSFORMERS_HOME=/workspace/.cache/sentence_transformers

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    ffmpeg \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7860"]